# Site settings
title: Gabriel Rezzonico
email: gabrielrezzonico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal online bussiness card, Its mainly a place to gather all my social media profiles. To make this site I have used jekyll, twitter bootstrap and font-awesome. 
  Its hosted at github as a github page.
  I would really like to see that you fork this code and find it useful. Please don't hesitate to contact me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabrielrezzonico.com" # the base hostname & protocol for your site
twitter_username: grezzonico
github_username:  gabrielrezzonico
facebook_username: gabrielrezzonico

# Build settings
markdown: kramdown

# google analytics
ga_tracking_id: UA-56331024-1