# Site settings
title: Gabriel Rezzonico
email: gabrielrezzonico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal online bussiness card, Its mainly a place to gather all my social media profiles. 
  I am available for hire to consult, advise, and develop with passionate teams across the globe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabrielrezzonico.com" # the base hostname & protocol for your site
twitter_username: grezzonico
github_username:  gabrielrezzonico
facebook_username: gabrielrezzonico

# Build settings
markdown: kramdown

# google analytics
ga_tracking_id: UA-56331024-1